### ISSUE TITLE
Ship the new website

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/Organizational-Development#1]
We need to ship the new website:
- [x] Give Kyle AWS access
- [x] Give Kyle Domain access
- [x] Deploy Brigadehub Site 
- [x] Whitelabel for C4SJ
- [x] Move Domain to point to new website

**Comment by Kyle-Falconer** [comment]
I need to get ahold of the domain name registrar details and also AWS hosting info.

**Comment by ghost** [comment]
This looks like it happened! The design looks great. Is that accurate?

**Comment by ghost** [comment]
Just talked to @3vivekb and he said it shipped! Closing.
